services:  # 1. BACKEND (Node.js) -> Konek ke Neon
  backend:
    build: ./be
    container_name: mbg_backend_neon
    ports:
      - "2001:2001"
    environment:
      - PGHOST=ep-raspy-rain-a1yesp8l-pooler.ap-southeast-1.aws.neon.tech
      - PGDATABASE=despro
      - PGUSER=neondb_owner
      - PGPASSWORD=npg_MJ2omC6tBpGf
      - PGSSLMODE=require
      - PGCHANNELBINDING=require
      - PGPORT=5432
      - AI_SERVICE_URL=http://localhost:8000/predict #ganti ke ip home server nahl pas udah deploy
      - PORT=2001
      - JWT_SECRET=rahasia_dapur_mbg_2025
    # Jadiin comment kalo udah deploy karena ai server ga di deploy pake vps
    depends_on:
      - ai-server # Backend nunggu AI Server siap

  # 2. AI SERVER (Python)
  # Jadi comment kalo udah deploy karena ai server ga di deploy pake vps
  ai-server:
    build: ./ai
    container_name: mbg_ai_local
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_MJ2omC6tBpGf@ep-raspy-rain-a1yesp8l-pooler.ap-southeast-1.aws.neon.tech/despro?sslmode=require&channel_binding=require
    ports:
      - "8000:8000"

  # 3. FRONTEND (React + Nginx)
  frontend:
    build: 
      context: ./fe
      args:
        - VITE_API_BASE_URL=http://localhost:2001
        - VITE_USE_MOCK=true
    container_name: mbg_frontend_local
    ports:
      - "80:80"
    depends_on:
      - backend

# Tidak butuh volumes database lagi karena data ada di Cloud